
OUTPUT_PATH = '/src/output'

CSV_NAME_ORIGINAL = 'src/data/data_last'
CSV_NAME_COLON = 'src/output/data_colons'
CSV_NAME_REPLACE = 'src/output/data_replace'
CSV_NAME_NULL = 'src/output/data_null'
CSV_NAME_POSITIVES = 'src/output/data_positives'
CSV_NAME_NEGATIVES = 'src/output/data_negatives'
CSV_NAME_POSITIVES_OUTLIERS = 'src/output/data_positives_outliers'
CSV_NAME_NEGATIVES_OUTLIERS = 'src/output/data_negatives_outliers'
CSV_NAME_EMPTY_VALUES = 'src/output/data_empty_values'
EXT_CSV = '.csv'

CSV_FILE = CSV_NAME_ORIGINAL + EXT_CSV
CSV_FILE_COLONS = CSV_NAME_COLON + EXT_CSV
CSV_FILE_REPLACE = CSV_NAME_REPLACE + EXT_CSV

CSV_FILE_NULL = CSV_NAME_NULL + EXT_CSV
CSV_FILE_POSITIVES = CSV_NAME_POSITIVES + EXT_CSV
CSV_FILE_NEGATIVES = CSV_NAME_NEGATIVES + EXT_CSV
CSV_FILE_POSITIVES_OUTLIERS = CSV_NAME_POSITIVES_OUTLIERS + EXT_CSV
CSV_FILE_NEGATIVES_OUTLIERS = CSV_NAME_NEGATIVES_OUTLIERS + EXT_CSV
CSV_FILE_EMPTY_VALUES = CSV_NAME_EMPTY_VALUES + EXT_CSV

NULL_VALUES = 'Null'
UPPER = 1000
LOWER = -1000
DELIMITER_SEMICOLON = ';'
DELIMITER_COLON = ','
EXTENSION = 'csv'
COLUMN_NUMBER = 1
SEARCH_VALUE = ","
REPLACE_VALUE = "."
COLUMN_NUMBER1 = 0
COLUMN_NUMBER2 = 1
