
CSV_PATH = 'C:/Users/coral/PycharmProjects/Python_project_2_fran/'
CSV_NAME_ORIGINAL = 'src/data/data_last'
CSV_NAME_REPLACE = 'src/output/data_replace'
CSV_NAME_NULL = 'src/output/data_null'
CSV_NAME_POSITIVES = 'src/output/data_positives'
CSV_NAME_NEGATIVES = 'src/output/data_negatives'
EXT_CSV = '.csv'

CSV_FILE = CSV_PATH + CSV_NAME_ORIGINAL + EXT_CSV

CSV_FILE_REPLACE = CSV_PATH + CSV_NAME_REPLACE + EXT_CSV

CSV_FILE_NULL = CSV_PATH + CSV_NAME_NULL + EXT_CSV
CSV_FILE_POSITIVES = CSV_PATH + CSV_NAME_POSITIVES + EXT_CSV
CSV_FILE_NEGATIVES = CSV_PATH + CSV_NAME_NEGATIVES + EXT_CSV


NULL_VALUES = 'Null'
UPPER = 1000
LOWER = -1000
DELIMITER_SEMICOLON = ';'
DELIMITER_COLON = ','
