import csv
import os


def current_directory():
    """
    Gets the directory you are currently working at.
    :return: the current working directory
    """
    return os.getcwd()


def remove_ext(path, ext):
    """
    Removes all files in a directory with the extension given.
    :param path: the path of the directory from where you want to remove all the files with the given extension.
    :param ext: the extension of the file you want to remove.
    :return: Nothing
    """
    for f in os.listdir(path):  # Go through all files in the directory. (f is a string of the name od the file)
        split_f = f.split(".")  # Splits the string f where there is a "." and it saves it in a list

        if split_f[-1] == ext:  # Compares the last item of the list with the parameter ext.
            os.remove(os.path.join(path, f))  # os.path.join, joins the path with the file name (this way we dont have
            # to create an intermediate variable), os.remove, removes it.


def replace(list_replace, column, search_v, replace_v):
    """
    Changes commas for dots.
    :param list_replace: the list from where we extract the values.
    :param column: the specific column where the number that we are looking for is at.
    :param search_v: the parameter we are searching for in the list.
    :param replace_v: the parameter we use to replace the search_v.
    :return: the new list generated by adding the values once the colons are replace with dots
    and the count of this new list.
    """
    list_replace_complete = []  # creating a new list
    count = 0  # count starts at 0
    for linea_i in list_replace:  # runs every element in the list
        # goes through every value in the specific column searching for the search_v and replacing it with the replace_v
        place = linea_i[column].replace(search_v, replace_v)
        linea_i[column] = place
        list_replace_complete.append(linea_i)  # once th replacing is done, it adds the values to the new list.
        count += 1  # It adds 1 with each new element added to the list.

    return list_replace_complete, count


def open_csv(new_file, delimiter_param):
    """
    Opens a file
    :param new_file: the file we want to open
    :param delimiter_param: the delimiter used in this file
    :return: the list of values in this file
    """
    with open(new_file) as data:  # open this file as data
        entry = csv.reader(data, delimiter=delimiter_param)  # reading the file as data and using the delimiter given
        list_i = list(entry)  # reading the file as a list
    return list_i


def create_csv(create_new_csv, csvlist, delimiter_param, column_lists):
    """
    Creates a new csv
    :param create_new_csv: the csv we are creating
    :param csvlist: the list we are putting into the csv
    :param delimiter_param: the delimiter we are using in our csv
    :param column_lists: the list of columns we are using in our csv
    :return: Nothing
    """
    output_f = open(create_new_csv, "w+")  # opens the new csv and writes on it
    csv_str = ""  # the text in our new csv

    for linea_i in csvlist:  # runs every element in the list for each line
        for column_i in column_lists:  # runs every element in the list for each column
            # add the text in each line and column using the delimiter given at the end of each element
            csv_str += str(linea_i[column_i]) + delimiter_param
        csv_str = csv_str[:-1] + '\n'  # add an enter at the end of each line

    output_f.write(csv_str)
    output_f.close()
