import csv
import os


def remove_csv(path):  # Method to remove all files in a directory, rem is the directory path.
    for f in os.listdir(path):
        extension = f.split(".")  # function that splits a string or list
        # print(extension)
        # print('looking at file ' + f)
        # print('comparing ' + extension[-1] + ' con ' + 'csv')  # comparing the last value of the above list [-1] with
        # the extension we are interested in this case csv.
        if extension[-1] == 'csv':
            # print('inside')  # printing to see whether this comparison works or not, if the extension is different
            # from csv then it will not appear inside.
            # print(type(extension))  # it prints the type of variable.
            os.remove(os.path.join(path, f))
        # print()


def list_of_colons(list_post):
    list_colons = []
    for linea_i in list_post:
        if linea_i[1].__contains__(","):
            list_colons.append(linea_i)
            # print(list_colons)

    return list_colons


def represents_int(s):  # Method that checks if a string is an integer
    try:
        int(s)
        return True
    except ValueError:
        return False


def represents_float(s):  # Method that checks if a string is a float
    try:
        float(s)
        return True
    except ValueError:
        return False


def positives(list_post, upper_post):
    """
    :param list_post: csv_new_list, it opens the new csv with the replaced delimiter.
    :param upper_post: upper constant 1000.
    :return: t returns the new list generated by adding the values that meet the if requirements.
    """
    list_post_complete = []
    for linea_i in list_post:
        # if linea_i[0] == "Sebastian Graham":
        # print(linea_i[1])
        if represents_int(linea_i[1]) or represents_float(linea_i[1]):  # call the method to check whether the value in
            # the second column (linea_i[1]) is a float or an integer
            # if linea_i[0] == "Sebastian Graham":
            # print("inside")
            if 0 < float(linea_i[1]) < upper_post:
                list_post_complete.append(linea_i)

    return list_post_complete  # return the list


def negatives(list_post, lower_post):
    """
    :param list_post: csv_new_list, it opens the new csv with the replaced delimiter.
    :param lower_post: lower constant -1000.
    :return:it returns the new list generated by adding the values that meet the if requirements.
    """
    list_neg_complete = []
    for linea_i in list_post:
        if represents_int(linea_i[1]) or represents_float(linea_i[1]):
            if 0 > float(linea_i[1]) > lower_post:
                list_neg_complete.append(linea_i)

    return list_neg_complete


def null(list_null, equal_null):
    """

    :param list_null: csvlist, it opens the original csv with the colon delimiter.
    :param equal_null: NULL_VALUES, it pass the string 'Null'
    :return: it returns the new list generated by adding the values that meet the if requirements, in this case the
    values that have the string 'Null'.
    """
    list_null_complete = []
    for linea_i in list_null:
        if linea_i[1] == equal_null:
            list_null_complete.append(linea_i)

    return list_null_complete


def replace(list_replace):  # new method to change commas for dots in the csv.
    """
    :param list_replace: csvlist, from the original csv with the colon delimiter.
    :return: it returns the new list generated by adding the values once the colons are replace with dots.
    """
    list_replace_complete = []
    for linea_i in list_replace:
        place = linea_i[1].replace(",", ".")  # function .replace to replace something in the csv.
        # print(place)
        linea_i[1] = place
        list_replace_complete.append(linea_i)
        # print(list_replace_complete)

    return list_replace_complete


def open_csv(new_file, delimiter_param):
    with open(new_file) as data:
        entry = csv.reader(data, delimiter=delimiter_param)
        list_i = list(entry)
    return list_i


def create_csv(create_new_csv, csvlist, delimiter_param):
    output_f = open(create_new_csv, "w+")
    csv_str = ""

    for linea_i in csvlist:
        csv_str += str(linea_i[0]) + delimiter_param + str(
            linea_i[1]) + '\n'

    output_f.write(csv_str)
    output_f.close()
